FROM --platform=linux/amd64 ubuntu:20.04 AS builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential

COPY . /repo
WORKDIR /repo
RUN make komplott

FROM ubuntu:20.04 AS package
COPY --from=builder /repo/komplott /
